#!/bin/sh

if [ "$#" -lt 5 ]; then
    echo "Numero incorrecto de parametros" 1>&2
    echo "Uso: $0 listaAlumnos res1parcial res1rec res2parcial res2rec" 1>&2
    exit 1
fi

tmpdir=$(mktemp -d)
TAB=$(printf "\t")

nombres="$1"

shift

c="1"

for i in "$@"; do
    cat "$i" |
        cut -d "$TAB" -f 1,3 |
        sort > "$tmpdir"/res"$c".csv
    c=$((c + 1))
done

sort "$nombres" |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 2.2" - "$tmpdir/"res1.csv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 2.2" - "$tmpdir/"res2.csv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 2.2" - "$tmpdir/"res3.csv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 1.5 2.2" - "$tmpdir/"res4.csv | 
    awk 'BEGIN{ FS="\t"; OFS=FS }
    {
        if(($3=="P")&&($5=="P")){
            nota="PROMOCION"
        } else if(($3=="P"||$3=="A"||$4=="A")&&($3=="P"||$5=="A"||$6=="A")){
            nota="APROBADO"
        } else if($3=="-"&&$4=="-"&&$5=="-"&&$6=="-"){
            nota="AUSENTE" 
        } else {
            nota="DESAPROBADO"
        }
        if($2=="N"){
            $2="FueraDeLista"
        }
        print $0,nota
    }' | sort -k 2 -t "$TAB"


rm -rf "$tmpdir"
