#!/bin/sh

if [ "$#" -lt 5 ]; then
    echo "Numero incorrecto de parametros" 1>&2
    echo "Uso: $0 listaAlumnos res1parcial res1rec res2parcial res2rec" 1>&2
    exit 1
fi

tmpdir=$(mktemp -d)
TAB=$(printf "\t")

nombres="$1"

shift

c="1"

for i in "$@"; do
    cat "$i" |
        cut -d "$TAB" -f 1,3 |
        sort > "$tmpdir"/res"$c".tsv
    c=$((c + 1))
done

sort "$nombres" |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 2.2" - "$tmpdir/"res1.tsv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 2.2" - "$tmpdir/"res2.tsv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 2.2" - "$tmpdir/"res3.tsv |
    join -t "$TAB" -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 1.5 2.2" - "$tmpdir/"res4.tsv |
    awk 'BEGIN{ FS="\t"; OFS=FS }
    {
        if(($3=="P")||($4=="P")){
            E1="P"
        } else if(($3=="A")||($4=="A")){
            E1="A"
        } else if(($3=="D")||($4=="D")){
            E1="D"
        } else {
            E1="-"
        }

        if(($5=="P")||($6=="P")){
            E2="P"
        } else if(($5=="A")||($6=="A")){
            E2="A"
        } else if(($5=="D")||($6=="D")){
            E2="D"
        } else {
            E2="-"
        }

        if((E1=="P")&&(E2=="P")){
            nota="PROMOCION"
        } else if((E1=="P"||E1=="A")&&(E2=="P"||E2=="A")){
            nota="APROBADO"
        } else if(E2=="-"&&E1=="-"){
            nota="AUSENTE" 
        } else {
            nota="DESAPROBADO"
        }
        if($2=="-"){
            $2="FueraDeLista"
        }
        print $0,nota
    }' | sort -k 2 -t "$TAB"

rm -rf "$tmpdir"
