#!/bin/sh

if [ "$#" -lt 5 ]; then
    echo "Numero incorrecto de parametros" 1>&2
    echo "Uso: $0 listaAlumnos res1parcial res1rec res2parcial res2rec" 1>&2
fi

tmpdir=$(mktemp -d)

nombres="$1"

shift

c="1"

for i in "$@"; do
    cat "$i" |
        awk 'BEGIN{ FS="\t"; OFS=FS }
        { if($3=="P"){$3="A"}; print $1,$3 }' |
        sort > "$tmpdir"/res"$c".csv
    c=$((c + 1))
done

cd "$tmpdir"

sort "$nombres" |
    join -t $'\t' -e "-" -a 1 -a 2 -o "0 1.2 2.2" - res1.csv |
    join -t $'\t' -e "-" -a 1 -a 2 -o "0 1.2 1.3 2.2" - res2.csv |
    join -t $'\t' -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 2.2" - res3.csv |
    join -t $'\t' -e "-" -a 1 -a 2 -o "0 1.2 1.3 1.4 1.5 2.2" - res4.csv | 
    awk 'BEGIN{ FS="\t"; OFS=FS }
    {
        if(($3=="A"||$4=="A")&&($5=="A"||$6=="A")){
            nota="APROBADO"
        } else if($3=="N"&&$4=="N"&&$5=="N"&&$6=="N"){
            nota="AUSENTE" 
        } else {
            nota="DESAPROBADO"
        }
        if($2=="N"){
            $2="FueraDeLista"
        }
        print $0,nota
    }' | sort -k 2 -t $'\t'


rm -rf "$tmpdir"
