#!/bin/sh

TAB=$(printf "\t")

# shellcheck disable=SC2016
rango='
BEGIN{
    alumnos=0
    FS="\t"
    OFS=FS
}

(!alumnos)&&/^Legajo/{
    alumnos=1
    print "AI"
    next
}

(!alumnos)&&/^N°/{
    alumnos=1
    print "AC"
    next
}

(!alumnos){
    next
}

{
    print $0
}
'


# shellcheck disable=SC2016
formato='
BEGIN{
    FS="\t"
    OFS=FS
}

(NR==1){
    if($1=="AI"){
        lr=1
        nr=2
    } else {
        lr=2
        nr=3
    }
    next
}

($lr==""){
    next
}

{
    leg_orig = $lr
    gsub(/.*-/,"", $lr)
    num_leg = sprintf("%06d", $lr)
    gsub("  *", " ", $nr)
    gsub("^ ", "", $nr)
    $nr = tolower($nr)
    split($nr, nombres, " ")
    nc=""
    for(i in nombres){
        n = nombres[i]
        sub(".", substr(toupper(n), 1,1) , n);
        nc = (nc " " n)
    }
    sub("^ ", "", nc)
    print num_leg, nc, leg_orig
}
'

tmpdir=$(mktemp -d)

libreoffice --headless --convert-to tsv:"Text - txt - csv (StarCalc)":9,34,UTF-8 "$@" --outdir "$tmpdir" 1>&2

for i in "$tmpdir"/*; do

    from=$(file -b --mime-encoding "$i")
    iconv -f "$from" -t "UTF-8" "$i" | awk "$rango"

done |
    awk "$formato" |
    sort -k 2 --field-separator="$TAB" |
    uniq

rm -rf "$tmpdir"
